stages:
  - tag

create-tag:
  stage: tag
  script:
    # Fetch the latest tag
    - latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
    # Parse the version numbers
    - IFS='.' read -r major minor patch <<< "${latest_tag#v}"
    # Increment the patch version
    - new_tag="v$major.$minor.$((patch + 1))"
    # Create and push the new tag
    - git tag -a "$new_tag" -m "Release $new_tag"
    - git push origin "$new_tag"
  only:
    - main
